import { useRef, useState } from "react";
import { Link } from "react-router-dom";
import { createRound, type Difficulty, type MathQuestion, type TopicSetting } from "./mathLogic";
import { QuestionVisual } from "./MathVisuals";

type Screen = "setup" | "practice" | "results";
type Result = { question: MathQuestion; firstTry: boolean; usedHint: boolean };
const topics: {value: TopicSetting; label: string; detail: string}[] = [
  {value:"addition",label:"Addition",detail:"Put groups together"},{value:"subtraction",label:"Subtraction",detail:"Take some away"},
  {value:"money",label:"Money",detail:"Coins, shopping, and change"},{value:"time",label:"Time",detail:"Read an analog clock"},{value:"mixed",label:"Mix it up",detail:"Two questions from every topic"},
];

export function MathAdventures() {
  const [screen,setScreen]=useState<Screen>("setup"), [topic,setTopic]=useState<TopicSetting>("addition"), [difficulty,setDifficulty]=useState<Difficulty>("starting");
  const [questions,setQuestions]=useState<MathQuestion[]>([]), [index,setIndex]=useState(0), [wrong,setWrong]=useState<string[]>([]), [hint,setHint]=useState(false), [correct,setCorrect]=useState(false), [results,setResults]=useState<Result[]>([]);
  const locked=useRef(false); const question=questions[index];
  const start=()=>{setQuestions(createRound(topic,difficulty));setIndex(0);setWrong([]);setHint(false);setCorrect(false);setResults([]);locked.current=false;setScreen("practice")};
  const answer=(choice:string)=>{if(locked.current||correct||wrong.includes(choice))return;if(choice===question.answer){locked.current=true;setCorrect(true);setResults(r=>[...r,{question,firstTry:wrong.length===0,usedHint:hint}]);}else setWrong(w=>[...w,choice]);};
  const next=()=>{if(index===questions.length-1){setScreen("results");return;}setIndex(i=>i+1);setWrong([]);setHint(false);setCorrect(false);locked.current=false;};
  const reset=()=>setScreen("setup");
  const nav=<nav className="game-nav"><Link to="/" className="back-link">← All helpers</Link><span className="mini-brand">Homework Helpers</span></nav>;
  if(screen==="setup")return <main className="game-shell math-shell">{nav}<section className="setup-card math-setup"><div className="setup-hero math-hero"><div className="math-hero-icon" aria-hidden="true">1+2</div><p className="eyebrow">First-grade math</p><h1>Math Adventures</h1><p>Pick a path and solve eight friendly problems at your own pace.</p></div><div className="setup-options"><fieldset><legend>1. Choose a topic</legend><div className="math-topic-grid">{topics.map(t=><label key={t.value} className={`selection-card ${topic===t.value?"selected":""}`}><input type="radio" name="topic" checked={topic===t.value} onChange={()=>setTopic(t.value)}/><span className="selection-check">✓</span><strong>{t.label}</strong><small>{t.detail}</small></label>)}</div></fieldset><fieldset><legend>2. Choose a level</legend><div className="segmented-control"><label className={difficulty==="starting"?"selected":""}><input type="radio" name="level" checked={difficulty==="starting"} onChange={()=>setDifficulty("starting")}/><span><strong>Starting out</strong><small>Numbers to 10 · coins to 20¢ · whole hours</small></span></label><label className={difficulty==="next"?"selected":""}><input type="radio" name="level" checked={difficulty==="next"} onChange={()=>setDifficulty("next")}/><span><strong>Next step</strong><small>Numbers to 20 · money to $1 · half hours</small></span></label></div></fieldset><button className="primary-button" onClick={start}>Start adventure →</button><p className="game-note">Untimed · 8 questions · hints whenever you need one</p></div></section></main>;
  if(screen==="results"){const first=results.filter(r=>r.firstTry).length, review=results.filter(r=>!r.firstTry||r.usedHint);return <main className="game-shell math-shell">{nav}<section className="results-card math-results"><div className="confetti">✦</div><p className="eyebrow">Adventure complete</p><h1>You did it!</h1><div className="score-ring" style={{"--score":`${first/8*360}deg`} as React.CSSProperties}><div><strong>{first}</strong><span>out of 8</span></div></div><p className="accuracy">answered correctly on the first try</p>{review.length?<div className="math-review"><h2>Problems you worked through</h2>{review.map((r,i)=><div key={r.question.id+i}><strong>{r.question.prompt}</strong><span>{r.question.explanation}</span></div>)}</div>:<p className="perfect-message">Every answer was right on the first try. Wonderful work!</p>}<div className="result-actions"><button className="primary-button" onClick={start}>Try a fresh round</button><button className="secondary-button" onClick={reset}>Choose another topic</button></div></section></main>}
  return <main className="game-shell math-shell play-shell"><nav className="game-nav"><button className="back-link plain-button" onClick={reset}>← End practice</button><div className="progress-copy">Question <strong>{index+1}</strong> of 8</div></nav><div className="progress-track"><span style={{width:`${((index+(correct?1:0))/8)*100}%`}}/></div><section className="question-area math-question"><p className="eyebrow">{question.topic} adventure</p><h1>{question.prompt}</h1><QuestionVisual question={question} hint={hint}/>{hint&&<div className="hint-panel"><strong>Here’s a hint</strong><p>{question.hint}</p></div>}<div className="choice-grid math-choices" aria-label="Answer choices">{question.choices.map(choice=><button key={choice} className={`choice-card ${correct&&choice===question.answer?"correct":wrong.includes(choice)?"incorrect":""}`} disabled={correct||wrong.includes(choice)} onClick={()=>answer(choice)}>{choice}{(wrong.includes(choice)||(correct&&choice===question.answer))&&<span className="answer-mark"/>}</button>)}</div><div className="math-actions">{!correct?<button className="secondary-button hint-button" onClick={()=>setHint(true)} disabled={hint}>💡 {hint?"Hint shown":"Hint"}</button>:<button className="primary-button" onClick={next}>{index===7?"See my results":"Next →"}</button>}</div><div className="feedback-message visible" aria-live="polite">{correct?`That’s right! ${question.explanation}`:wrong.length?"Good try. Pick another answer.":""}</div></section></main>;
}
